SMDX_METADATA_CONCEPTS: SDMX Metadata Concepts
INDICATOR_NUMBER: 'Indicator: %number'
DOWNLOAD_PDF: Download PDF
REVISION_HISTORY: Revision history
TESTING: Praesent sit amet facilisis metus, vel gravida ante. Quisque interdum massa id leo varius posuere. Maecenas tincidunt ornare odio ac tempor. Integer eros ligula, convallis et vestibulum sit amet, maximus sit amet lacus. Nam rutrum augue sapien, a tristique nisi eleifend vitae. Integer malesuada sem tristique urna feugiat posuere. Donec ullamcorper sit amet justo at mollis. Nam odio elit, vehicula sed nisl at, vulputate viverra elit.