theme: jekyll-theme-slate

title: SDG Metadata Translation Pilot
description: Evaluating Machine Translation of Indicator Metadata for the Sustainable Development Goals

languages:
  en: English
  ru: Russian
