SMDX_METADATA_CONCEPTS: Концепции SDMX метаданных
INDICATOR_NUMBER: 'Покказатель: %number'
DOWNLOAD_PDF: Скачать PDF
REVISION_HISTORY: ''
TESTING: Morbi non enim dapibus, scelerisque leo non, finibus dolor. Nulla non turpis
  quis tortor tempus viverra nec vel metus. Integer ut tristique turpis. Nam tincidunt
  lobortis ipsum vel tempus. Pellentesque venenatis leo cursus, ultricies leo quis,
  interdum purus. Vivamus feugiat nisl sed tortor vulputate, eget interdum sapien
  accumsan. Phasellus sollicitudin euismod porta. Donec efficitur ornare commodo.
  Praesent tincidunt leo non consectetur malesuada.
